### ISSUE TITLE
Could this be used for inpainting models?

### ISSUE THREAD

**Issue by ShashwatNigam99** [KU-CVLAB/DreamMatcher#1]
Would love to see if it's possible to use this approach for inpainting areas using an image as reference

**Comment by nam-jisu** [comment]
Hi,

Thank you for your interest in our work.

Our framework is based on semantic matching between the subjects in target and reference images, making it uncertain for direct application in inpainting tasks. However, if you share more details about your goals, we might discuss the possibilities together.

Thanks.
