### ISSUE TITLE
Question about support XL 

### ISSUE THREAD

**Issue by nullarch** [KU-CVLAB/DreamMatcher#3]
First of all, thank you very much for conducting research on such an excellent topic.

It seems that this paper is based on training with stable diffusion 1.5.

Do you have plans to train with the diffusion XL model in the future?

I am curious about the milestones for whether this project will have additional updates in the future.

thank you!

**Comment by nam-jisu** [comment]
Hi,

Thanks for your interest and great suggestion.

We're currently exploring the possibility of incorporating the diffusion XL model into our code. 
Once our experiments conclude, we'll update the code accordingly.

Thanks again.

**Comment by plastic0313** [comment]
> Hi,
> 
> Thanks for your interest and great suggestion.
> 
> We're currently exploring the possibility of incorporating the diffusion XL model into our code. Once our experiments conclude, we'll update the code accordingly.
> 
> Thanks again.

Very meaningful work, looking forward to your release of more SD XL experimental results, do you have the approximate time of release of this part of the work？

**Comment by nam-jisu** [comment]
Thank you for your answer.

Due to the resource limitation, we couldn't personalize SDXL.
However, we recommend [https://civitai.com/], which provides massive personalized SDXL models.

You can simply replace the pre-trained weights and pipeline with SDXL.

Thanks.
