### ISSUE TITLE
About modifications diffusers version  

### ISSUE THREAD

**Issue by RayleighChen** [KU-CVLAB/DreamMatcher#4]
Thank you for the great work on this project. In relation to that, I am looking to ascertain the specific commit of the ```diffusers``` library that the set of modifications is based on. My aim is to examine the crucial code changes to understand the extent of modifications and explore possibilities for simplification.

Could you share the commit hash about the base ```diffusers```?  Thank you for your time and assistance.

**Comment by nam-jisu** [comment]
Thank you for your interest in our work.

Our code builds on base diffusers, with a modification for feature extraction to achieve semantic matching. 

The only modification within the diffusers can be found in `UNet2DConditionModel` at `diffusers/src/diffusers/models/unet_2d_condition.py.`

Using these descriptors, our DreamMatcherPipeline introduces the proposed attention module atop the diffusers U-Net, as detailed in `run_dreammatcher.py.`

We plan to make our code available in diffusers for easier use.

Thanks.
