### ISSUE TITLE
Will the training code be released?

### ISSUE THREAD

**Issue by rivaldophilip** [KU-CVLAB/DreamMatcher#5]
Love the work and would love to try training some models. Could I ask if there are plans to release the training code? Thank you!

**Comment by nam-jisu** [comment]
Hi,

Thank you for your interest in our work.

DreamMatcher is a plug-in model compatible with any off-the-shelf personalized models. 
In our codebase, we use Textual Inversion, DreamBooth, and CustomDiffusion as baselines, following their training code from their respective GitHub repositories.

Thanks.

**Comment by shoutOutYangJie** [comment]
> Hi,
> 
> Thank you for your interest in our work.
> 
> DreamMatcher is a plug-in model compatible with any off-the-shelf personalized models. In our codebase, we use Textual Inversion, DreamBooth, and CustomDiffusion as baselines, following their training code from their respective GitHub repositories.
> 
> Thanks.

Can I directly apply it on a common diffusion model, rather than a trained personalized models

**Comment by nam-jisu** [comment]
Hi,

Thank you for your interest in our work.

We've included experiments on Stable Diffusion 1.5 in the Appendix of our paper.

However, it's important to note that our model is designed as a tuning-free plug-in. This means that if the baseline produces too poor quality images, semantic matching may sometimes fail.

Therefore, we strongly recommend using off-the-shelf personalized models like Textual Inversion, Dreambooth, or CustomDiffusion for optimal results.

We also provide the pre-trained baseline weights you can easily use.

Thanks.
