### ISSUE TITLE
Can I directly apply it on a common diffusion model, rather than a trained personalized models

### ISSUE THREAD

**Issue by shoutOutYangJie** [KU-CVLAB/DreamMatcher#6]
It seem that DreamMatcher must be apply in a personlizing model?

If I apply it on some common model, such as original sd1.5 or sdxl, can it still work?
very look forward to your reply

**Comment by nam-jisu** [comment]
Hi,

Thank you for your interest in our work.

We've included experiments on Stable Diffusion 1.5 in the Appendix of our paper. 

However, it's important to note that our model is designed as a tuning-free plug-in. This means that if the baseline produces too poor quality images, semantic matching may sometimes fail. 

Therefore, we strongly recommend using off-the-shelf personalized models like Textual Inversion, Dreambooth, or CustomDiffusion for optimal results. 

We also provide the pre-trained baseline weights you can easily use.

Thanks.
