### ISSUE TITLE
Your code has some error.

### ISSUE THREAD

**Issue by shoutOutYangJie** [KU-CVLAB/DreamMatcher#7]
![image](https://github.com/KU-CVLAB/DreamMatcher/assets/46734514/072450df-7530-4465-9ab6-86185e5be074)

It seem that you re-define this unet block's forward function, but you donot upload it

**Comment by shoutOutYangJie** [comment]
I got a mistake. 
Nothing happen

**Comment by zhang2002forwin** [comment]
Hello，do you solve it?  I have the same problem.

**Comment by zhang2002forwin** [comment]
> Hello，do you solve it? I have the same problem.

Oh,  I  skip the two steps:`cd diffusers` and `pip install -e .`
Thanks for your attention.
