### ISSUE TITLE
I try to generate consistent anime character using your method, but I got bad result.

### ISSUE THREAD

**Issue by shoutOutYangJie** [KU-CVLAB/DreamMatcher#8]
<img width="954" alt="image" src="https://github.com/KU-CVLAB/DreamMatcher/assets/46734514/4f5f0011-24a5-4533-99af-1eac3494f18a">

I find your method will decrease image quality. first column is reference image, other column is output image according to different prompts.

**Comment by nam-jisu** [comment]
Thank you for your interest in our work. 

Could you share with us which diffusion model you used and what the results were without our method?

Thanks.

**Comment by shoutOutYangJie** [comment]
> Thank you for your interest in our work.
> 
> Could you share with us which diffusion model you used and what the results were without our method?
> 
> Thanks.

anything v3.  image  from 2nd colmun to 5-th colmun is generated from your code

**Comment by nam-jisu** [comment]
Thank you for your answer.

In our paper, we used pre-trained personalized models on a specific concept.
However, it seems that you used pre-trained diffusion models on animation "style", not on a certain concept.
I think it could degrade the overall image quality.

How about using personalized models on your own characters using 5-7 input images, just like DreamBooth?

Thanks.
