### ISSUE TITLE
I want to know the reason for you to use the attn map correspond to "cat_statue" not the word "sks" for dreambooth

### ISSUE THREAD

**Issue by zhangh0920** [KU-CVLAB/DreamMatcher#9]

**Comment by zhangh0920** [comment]
Do you have try on using the aggregation attn map correspond to "sks cat_statue"

**Comment by nam-jisu** [comment]
Thank you for your interest in our work.

We've also tried to obtain the foreground mask from "sks," and found that there was no critical difference.
However, I think using aggregated attention maps from "sks cat_statue" might improve mask quality.

Thank you for your suggestion.

Thanks.
